#!/bin/bash

function main(){
	echo "<$(basename "$0")>$1" :: `date`

	local BASE='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		configure)
			"${BASE}/${REPO}/src/clone-${REPO}.sh"

		;;
		abort-upgrade|abort-remove|abort-deconfigure)
			echo -n

		;;
		*)
		echo "$0 called with unknown argument \`\$1'" >&2
		exit 0

		;;
	esac
}
main "$@"
