#!/bin/bash

function main(){
	date | tag "$@"

	local ROOT='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		configure)
			tag "$@" <<< "Launching \"clone-${REPO}.sh\""			
			"${ROOT}/${REPO}/src/clone-${REPO}.sh"

		;;
		abort-upgrade|abort-remove|abort-deconfigure)
			echo -n

		;;
		*)
			tag "$@" <<< "Called with unknown argument"
			exit 0

		;;
	esac
}
function tag(){
	local TAG="<$(basename "$0")> $1 ::"
	sed "s/^/${TAG} /"
}
function scroll(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
function enclose(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
main "$@"
