#!/bin/bash

function tag(){
	local TAG="<$(basename "$0")> $1 ::"
	sed "s/^/${TAG} /"
}
function main(){
	date | tag "$@"

	local BASE='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		configure)
			tag "$@" <<< "Launching \"clone-${REPO}.sh\""			
			"${BASE}/${REPO}/src/clone-${REPO}.sh"

		;;
		abort-upgrade|abort-remove|abort-deconfigure)
			echo -n

		;;
		*)
			tag "$@" <<< "Called with unknown argument"
			exit 0

		;;
	esac
}
main "$@"
