#!/bin/bash

function main(){
	date | tag "$@"

	local ROOT='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		remove)
			tag "$@" <<< "Removing \"${ROOT}/${REPO}\""
			rm -rfv "${ROOT}/${REPO}/{bin,doc,.git,lib,tmp}" | scroll

		;;
		upgrade)
			echo -n

		;;
		purge)
			tag "$@" <<< "Removing \"${ROOT}/${REPO}\""
			rm -rfv "${ROOT}/${REPO}" | scroll

		;;
		failed-upgrade|abort-install|abort-upgrade|disappear)
			echo -n

		;;
		*)
			tag "$@" <<< "Called with unknown argument"
			exit 0

		;;
	esac
}
function tag(){
	local TAG="<$(basename "$0")> $1 ::"
	sed "s/^/${TAG} /"
}
function scroll(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
function enclose(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
main "$@"
