#!/bin/bash

function main(){
	date | tag "$@"

	local ROOT='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		remove)
			tag "$@" <<< "Listing \"${ROOT}/${REPO}\""
				ls -R "${ROOT}/${REPO}" |
				sed '/^total /d;/^$/d;/:$/!{s/^/   /}' |
				scroll

			tag "$@" <<< "Removing \"${ROOT}/${REPO}\"/src/${REPO}-<unpacked packages>"
				find "${ROOT}/${REPO}/src" -maxdepth 1 -type d -name "${REPO}*" -exec rm -rvf  '{}' ';' |
				scroll

			tag "$@" <<< "Removing \"${ROOT}/${REPO}/.git\""
				rm -rf "${ROOT}/${REPO}/.git"

			tag "$@" <<< "Removing \"${ROOT}/${REPO}\" ... tmp* files"
				find "${ROOT}/${REPO}" -type f -name "tmp*" -exec rm -vf  '{}' ';' |
				scroll

			tag "$@" <<< "Removing \"${ROOT}/${REPO}\" ... empty directories"
				find "${ROOT}/${REPO}" -type d -empty -exec rm -rvf  '{}' ';' |
				scroll

		;;
		upgrade)
			echo -n

		;;
		purge)
			tag "$@" <<< "Listing \"${ROOT}/${REPO}\""
				ls -R "${ROOT}/${REPO}" |
				sed '/^total /d;/^$/d;/:$/!{s/^/   /}' |
				scroll
			tag "$@" <<< "Purging \"${ROOT}/${REPO}\""
				rm -rf "${ROOT}/${REPO}"

		;;
		failed-upgrade|abort-install|abort-upgrade|disappear)
			echo -n

		;;
		*)
			tag "$@" <<< "Called with unknown argument"
			exit 0

		;;
	esac
}
function tag(){
	local TAG="<$(basename "$0")> $1 ::"
	sed "s/^/${TAG} /"
}
function scroll(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
function enclose(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
main "$@"
