#!/bin/bash

function main(){
	local BASE='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		remove)
			echo "$1" :: `date`
			rm -rfv "${BASE}/${REPO}/"*

		;;
		upgrade)
			echo "$1" :: `date`

		;;
		purge|failed-upgrade|abort-install|abort-upgrade|disappear)
			echo "$1" :: `date`

		;;
		*)
		echo "postrm called with unknown argument \`\$1'" >&2
		exit 0

		;;
	esac
}
main "$@"
