#!/bin/bash

function tag(){
	local TAG="<$(basename "$0")>$1 ::"
	sed "s/^/${TAG} /"
}
function main(){
	date | tag "$@"

	local BASE='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

	case "$1" in
		remove)
			echo Removing \"${BASE}/${REPO}\" | tag "$@"
			rm -rf "${BASE}/${REPO}/{bin,doc,.git,lib,tmp}"

		;;
		upgrade)
			echo -n

		;;
		purge)
			Removing \"${BASE}/${REPO}\" | tag "$@"
			rm -rf "${BASE}/${REPO}"

		;;
		failed-upgrade|abort-install|abort-upgrade|disappear)
			echo -n

		;;
		*)
		echo "$0 called with unknown argument \`\$1'" >&2
		exit 0

		;;
	esac
}
main "$@"
