#!/bin/bash

function main(){
	date | tag "$@"

	local ROOT='/usr/local/share'
	local REPO='clixs'
	local GIT='michaelsalisbury'

}
function tag(){
	local TAG="<$(basename "$0")> $1 ::"
	sed "s/^/${TAG} /"
}
function scroll(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
function enclose(){
	if [ -x "${ROOT}/${REPO}/bin/${FUNCNAME}.sh" ]; then
		"${ROOT}/${REPO}/bin/${FUNCNAME}.sh" "$@"
	else
		cat
	fi
}
main "$@"
